### ISSUE TITLE
redhat7.3 beta install failed on garrison. 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1766]
I got the rh73 beta from ftp://ftp3.linux.ibm.com/redhat/beta_cds/RHEL-7.3-Beta-1/Server/ppc64le/iso/
put at: 
/root/Downloads/RHEL-7.3-20160817.1-Server-ppc64le-dvd1.iso
# ls -l /root/Downloads/RHEL-7.3-20160817.1-Server-ppc64le-dvd1.iso
-rw-r--r-- 1 root root 3192926208 Aug 24 13:02 /root/Downloads/RHEL-7.3-20160817.1-Server-ppc64le-dvd1.iso

then I ran 
copycds -n rhels7.3 -p /install/rhels7.3beta RHEL-7.3-20160817.1-Server-ppc64le-dvd1.iso
After it completed
I saw the osimage created for it: 
````
[root@c712ems4 zww]# lsdef -t osimage rhels7.3-ppc64le-install-compute
Object name: rhels7.3-ppc64le-install-compute
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.3-ppc64le
    osname=Linux
    osvers=rhels7.3
    otherpkgdir=/install/post/otherpkgs/rhels7.3/ppc64le
    pkgdir=/install/rhels7.3beta
    pkglist=/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/rh/compute.rhels7.tmpl

nodeset c712f7n02-pvt osimage=rhels7.3-ppc64le-install-compute
rsetboot it to net
rpower it boot
````

then It stopped with below error: 
````
Starting installer, one moment...
 * installation log files are stored in /tmp during the installation
 * shell is available on TTY2
 * when reporting a bug add logs from /tmp as separate text/plain attachments
07:57:17 Running pre-installation scripts
Traceback (most recent call last):
  File "/sbin/anaconda", line 1202, in <module>
    networkInitialize(ksdata)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/network.py", line 1304, in networkInitialize
    devnames = apply_kickstart(ksdata)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/network.py", line 1269, in apply_kickstart
    nm.nm_activate_device_connection(dev_name, con_uuid)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/nm.py", line 873, in nm_activate_device_connection
    raise SettingsNotFoundError(con_uuid)
pyanaconda.nm.SettingsNotFoundError: SettingsNotFoundError('98536515-1017-4738-ae44-8e70194b037f',)
Exception AttributeError: "'NoneType' object has no attribute 'udev_unref'" in <bound method Context.__del__ of <pyudev.core.Context object at 0x3fff8bf19150>> ignored

Pane is dead
[attached] 
````

````
 [root@c712ems4 ~]# lsxcatd -v
Version 2.12.2 (git commit e4a7359d31008d81c4c57e0857d5f09009a3269c, built Thu Aug 18 06:43:29 EDT 2016)
````

**Comment by immarvin** [comment]
open a ticket to LTC
https://bugzilla.linux.ibm.com/show_bug.cgi?id=145512

**Comment by whowutwut** [comment]
Thanks @immarvin  for opening the issue to LTC

**Comment by immarvin** [comment]
some updates on this:

The same issue can be recreated on power LE kvm node.

if I modify the line "network --onboot=yes --bootproto=dhcp --device=42:dc:da:97:e5:ab" in kickstart response file "/install/autoinst/NODE" to "network --onboot=yes --bootproto=dhcp ", The node can be installed, however, the NICs seems can not be activated:
````
[root@localhost ~]# vi /etc/sysconfig/network-scripts/ifcfg-eth0
NAME="eth0"
ONBOOT=yes
NETBOOT=yes
IPV6INIT=yes
UUID=xxxxxx(some number)
BOOTPROTO=dhcp
TYPE=Ethernet
[root@localhost ~]# ifup eth0
ERROR    : [/etc/sysconfig/network-scripts/ifup-eth] Device  does not seem to be present, delaying initialization.
[root@localhost ~]#
[root@localhost ~]# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@localhost ~]# udevadm info /sys//class/net/eth0
P: //devices/pci0000:00/0000:00:01.0/virtio0/net/eth0
E: DEVPATH=//devices/pci0000:00/0000:00:01.0/virtio0/net/eth0
E: ID_BUS=pci
E: ID_MODEL_FROM_DATABASE=Virtio network device
E: ID_MODEL_ID=0x1000
E: ID_NET_DRIVER=virtio_net
E: ID_NET_NAME_MAC=enx42dcda97e5ab
E: ID_PATH=virtio-pci-0000:00:01.0
E: ID_PATH_TAG=virtio-pci-0000_00_01_0
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Red Hat, Inc
E: ID_VENDOR_ID=0x1af4
E: IFINDEX=2
E: INTERFACE=eth0
E: SUBSYSTEM=net
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/eth0
E: TAGS=:systemd:
E: USEC_INITIALIZED=85255
 
````

**Comment by immarvin** [comment]
The problem has been fixed in the rhels7.3 snapshot1
