### ISSUE TITLE
rhel7.3 install fails during xcat kernel startup

### ISSUE THREAD

**Issue by jsimpson2** [xcat2/xcat-core#2019]
````
[    7.545160] drivers/rtc/hctosys.c: unable to open rtc device (rtc0)
[   14.379147] dracut-initqueue[1429]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[   14.379997] dracut-initqueue[1429]: Dload  Upload   Total   Spent    Left  Speed
 96  287M   96  276M    0     0  11.2M      0  0:00:25  0:00:24  0:00:01 11.2M   0 --:--:-- --:--:-- --:--:--     0
100  287M  100  287M    0     0  11.2M      0  0:00:25  0:00:25 --:--:-- 11.2M
[   40.765195] dracut-initqueue[1429]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[   40.766092] dracut-initqueue[1429]: Dload  Upload   Total   Spent    Left  Speed
100 78150  100 78150    0     0  9733k      0 --:--:-- --:--:-- --:--:-- 10.6M   0 --:--:-- --:--:-- --:--:--     0
[  OK  ] Started dracut initqueue hook.
         Starting dracut pre-mount hook...
[  OK  ] Reached target Remote File Systems (Pre).
[  OK  ] Reached target Remote File Systems.
[  OK  ] Started dracut pre-mount hook.
[  OK  ] Reached target Initrd Root File System.
         Starting Reload Configuration from the Real Root...
[  OK  ] Started Reload Configuration from the Real Root.
         Starting dracut mount hook...
[  OK  ] Reached target Initrd File Systems.
[  OK  ] Started dracut mount hook.
[  OK  ] Reached target Initrd Default Target.
         Starting dracut pre-pivot and cleanup hook...
[  OK  ] Started dracut pre-pivot and cleanup hook.
         Starting Cleaning Up and Shutting Down Daemons...
[  OK  ] Stopped target Timers.
[  OK  ] Stopped Cleaning Up and Shutting Down Daemons.
[  OK  ] Stopped dracut pre-pivot and cleanup hook.
         Stopping dracut pre-pivot and cleanup hook...
[  OK  ] Stopped target Remote File Systems.
[  OK  ] Stopped target Remote File Systems (Pre).
[  OK  ] Stopped target Initrd Default Target.
[  OK  ] Stopped dracut mount hook.
         Stopping dracut mount hook...
[  OK  ] Stopped target Basic System.
[  OK  ] Stopped target Sockets.
[  OK  ] Closed Open-iSCSI iscsiuio Socket.
[  OK  ] Stopped target Slices.
[  OK  ] Stopped target Paths.
[  OK  ] Stopped target System Initialization.
[  OK  ] Stopped target Local File Systems.
[  OK  ] Stopped target Swap.
[  OK  ] Stopped Apply Kernel Variables.
         Stopping Apply Kernel Variables...
[  OK  ] Stopped dracut pre-mount hook.
         Stopping dracut pre-mount hook...
[  OK  ] Stopped dracut initqueue hook.
         Stopping dracut initqueue hook...
         Stopping Open-iSCSI...
[  OK  ] Stopped target Encrypted Volumes.
[  OK  ] Stopped Open-iSCSI.
         Stopping Device-Mapper Multipath Device Controller...
[  OK  ] Stopped Device-Mapper Multipath Device Controller.
[  OK  ] Stopped udev Coldplug all Devices.
         Stopping udev Coldplug all Devices...
[  OK  ] Stopped dracut pre-trigger hook.
         Stopping dracut pre-trigger hook...
         Stopping udev Kernel Device Manager...
[  OK  ] Stopped udev Kernel Device Manager.
[  OK  ] Stopped Create Static Device Nodes in /dev.
         Stopping Create Static Device Nodes in /dev...
[  OK  ] Stopped Create list of required sta...ce nodes for the current kernel.
         Stopping Create list of required st... nodes for the current kernel...
[  OK  ] Stopped dracut pre-udev hook.
         Stopping dracut pre-udev hook...
[  OK  ] Stopped dracut cmdline hook.
         Stopping dracut cmdline hook...
[  OK  ] Closed udev Kernel Socket.
[  OK  ] Closed udev Control Socket.
         Starting Cleanup udevd DB...
[  OK  ] Started Cleanup udevd DB.
[  OK  ] Reached target Switch Root.
         Starting Switch Root...
[  OK  ] Started Show Plymouth Boot Screen.
[  OK  ] Started Device-Mapper Multipath Device Controller.
[  OK  ] Created slice system-lvm2\x2dpvscan.slice.
         Starting LVM2 PV scan on device 8:17...
[  OK  ] Reached target Paths.
[  OK  ] Started LVM2 PV scan on device 8:17.
[  OK  ] Started Initialize the iWARP/InfiniBand/RDMA stack in the kernel.
[  OK  ] Started udev Wait for Complete Device Initialization.
         Starting Activation of DM RAID sets...
[  OK  ] Started Activation of DM RAID sets.
[  OK  ] Reached target Local File Systems.
         Starting Rebuild Journal Catalog...
         Starting Tell Plymouth To Write Out Runtime Data...
         Starting Import network configuration from initramfs...
[  OK  ] Reached target Encrypted Volumes.
[  OK  ] Started Tell Plymouth To Write Out Runtime Data.
[  OK  ] Started Rebuild Journal Catalog.
         Starting Update is Completed...
[  OK  ] Started Update is Completed.
[  OK  ] Started Import network configuration from initramfs.
         Starting Create Volatile Files and Directories...
[  OK  ] Started Create Volatile Files and Directories.
         Starting Update UTMP about System Boot/Shutdown...
[  OK  ] Started Update UTMP about System Boot/Shutdown.
[  OK  ] Reached target System Initialization.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Listening on Open-iSCSI iscsiuio Socket.
[  OK  ] Listening on Open-iSCSI iscsid Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Reached target Basic System.
         Starting Terminate Plymouth Boot Screen...
         Starting Login Service...
[  OK  ] Started Anaconda NetworkManager configuration.
         Starting Anaconda NetworkManager configuration...
         Starting Dump dmesg to /var/log/dmesg...
         Starting Service enabling compressing RAM with zRam...
         Starting Wait for Plymouth Boot Screen to Quit...
[  OK  ] Started Hardware RNG Entropy Gatherer Daemon.
         Starting Hardware RNG Entropy Gatherer Daemon...
         Starting firewalld - dynamic firewall daemon...
 * installation log files are stored in /tmp during the installation
 * shell is available on TTY2
 * when reporting a bug add logs from /tmp as separate text/plain attachments
21:28:17 Running pre-installation scripts
Traceback (most recent call last):
  File "/sbin/anaconda", line 1202, in <module>
    networkInitialize(ksdata)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/network.py", line 1304, in networkInitialize
    devnames = apply_kickstart(ksdata)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/network.py", line 1269, in apply_kickstart
    nm.nm_activate_device_connection(dev_name, con_uuid)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/nm.py", line 873, in nm_activate_device_connection
    raise SettingsNotFoundError(con_uuid)
pyanaconda.nm.SettingsNotFoundError: SettingsNotFoundError('87836671-27e5-4010-b402-869c12e71b57',)
Exception AttributeError: "'NoneType' object has no attribute 'udev_unref'" in <bound method Context.__del__ of <pyudev.core.Context object at 0x3fffa16d4450>> ignored

Pane is dead
    raise SettingsNotFoundError(con_uuid)
pyanaconda.nm.SettingsNotFoundError: SettingsNotFoundError('87836671-27e5-4010-b402-869c12e71b57',)

Exception AttributeError: "'NoneType' object has no attribute 'udev_unref'" in <bound method Context.__del__ of <pyudev.core.Context object at 0x3fffa16d4450>> ignored

Pane is dead
[anaconda] 1:main
````

Here is the node definition:

ls[root@p10xcat1 ~]# lsdef p10a109
Object name: p10a109
    addkcmdline=modprobe.blacklist=nvidiafb
    arch=ppc64le
    bmc=129.40.41.109
    bmcpassword=admin
    bmcusername=ADMIN
    cons=ipmi
    cpucount=160
    cputype=POWER8NVL (raw), altivec supported
    currchain=boot
    currstate=install rhels7.3-ppc64le-compute
    disksize=sda:960GB,sdb:960GB
    groups=all
    initrd=xcat/osimage/rhels7.3-ppc64le-install-compute/initrd.img
    ip=129.40.42.109
    kcmdline=quiet inst.repo=http://!myipfn!:80/install/rhels7.3/ppc64le inst.ks=http://!myipfn!:80/install/autoinst/p10a109 BOOTIF=70:e2:84:14:17:79  ip=dhcp
    kernel=xcat/osimage/rhels7.3-ppc64le-install-compute/vmlinuz
    mac=70:e2:84:14:17:78!*NOIP*|70:e2:84:14:17:79
    memory=523125MB
    mgt=ipmi
    mtm=8335-GTB
    netboot=petitboot
    nodetype=mp
    os=rhels7.3
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=rhels7.3-ppc64le-install-compute
    serial=210D1AA
    status=installing
    statustime=10-24-2016 17:28:18
    supportedarchs=ppc64
    updatestatus=synced
    updatestatustime=10-21-2016 09:15:25
[root@p10xcat1 ~]#

**Comment by immarvin** [comment]
seems a duplicate bug with https://github.com/xcat2/xcat-core/issues/1766

hi @jsimpson2 , which redhat7.3 iso are you using? we found the same issue with redhat7.3 beta, and the issue has been fixed in redhat7.3 snap1, the latest redhat7.3 is rc2.

**Comment by jsimpson2** [comment]
Thanks for this info.  Would you possibly have a link to the latest 7.3 rc2? 

Will give that a try in the morning. 

Thanks! 

John 

Sent from IBM Verse


   yangsong --- Re: [xcat2/xcat-core] rhel7.3 install fails during xcat kernel startup (#2019) --- 
    From:"yangsong" <notifications@github.com>To:"xcat2/xcat-core" <xcat-core@noreply.github.com>Cc:"John Simpson" <john_simpson@us.ibm.com>, "Mention" <mention@noreply.github.com>Date:Mon, Oct 24, 2016 9:25 PMSubject:Re: [xcat2/xcat-core] rhel7.3 install fails during xcat kernel startup (#2019)
  
  seems a duplicate bug with #1766 
 hi @jsimpson2 , which redhat7.3 iso are you using? we found the same issue with redhat7.3 beta, and the issue has been fixed in redhat7.3 snap1, the latest redhat7.3 is rc2.

**Comment by whowutwut** [comment]
@jsimpson2  You can get it from ftp3.linux.ibm.com
