### ISSUE TITLE
2.11 build failed with /xpod2man: pods/man1/renergy.1.pod unexpected =item directive in paragraph 309.  ignoring.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#433]
ERROR:root:./xpod2man: pods/man1/renergy.1.pod: unexpected =item directive in paragraph 309.  ignoring.
Traceback (most recent call last):
  File "/media/xcat/build/xcat2_autobuild/buildxcat.py", line 133, in main
    buildxCAT(args, logger)
  File "/media/xcat/build/xcat2_autobuild/buildxcat.py", line 55, in buildxCAT
    linuxRPM.buildxCAT(args,logger)
  File "/media/xcat/build/xcat2_autobuild/xcatlib/linux_rpm.py", line 193, in buildxCAT
    raise Exception(err)
Exception: ./xpod2man: pods/man1/renergy.1.pod: unexpected =item directive in paragraph 309.  ignoring.

CRITICAL:root:<== Build ERRORS
FATAL ERROR building branch master, cannot continue

**Comment by zet809** [comment]
Fixed with pull request 434.

**Comment by tingtli** [comment]
Verified and close
