### ISSUE TITLE
[fvt][xcat-inventory]  xcat-inventory did not handle python internal error well

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4631]
``xcat-inventory`` did not handle internal error well, It throws out python error to STDOUT directly.

For example:

```
[root@c910f03c05k08 home]# xcat-inventory export --format=json -t aaa
Traceback (most recent call last):
  File "/opt/xcat/lib/python/xcclient/inventory/shell.py", line 51, in main
    InventoryShell('xcat-inventory').run(sys.argv[1:], '1.0', "xCAT inventory management tool")
  File "/opt/xcat/lib/python/xcclient/shell.py", line 184, in run
    return args.func(args)
  File "/opt/xcat/lib/python/xcclient/inventory/shell.py", line 41, in do_export
    mgr.validate_args(args, 'export')
  File "/opt/xcat/lib/python/xcclient/inventory/manager.py", line 97, in validate_args
    raise CommandException("Invalid object type: %(t)s", t=args.type)
CommandException: Invalid object type: aaa
```

**Comment by hu-weihua** [comment]
link to #4565

**Comment by immarvin** [comment]
fixed in https://github.ibm.com/HPC-Next/xCAT-Incubator/pull/1
```
[root@c910f03c05k21 xCAT-Incubator]# xcat-inventory export --format=json -t aaa
Error: Invalid object type: aaa
[root@c910f03c05k21 xCAT-Incubator]# echo $?
1
```
