### ISSUE TITLE
[fvt][xcat-inventory] xcat-inventory did not handle invalid json and yaml file very well

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4638]
``xcat-inventory`` did not handle invalid json and yaml file very well.  
Suggest to handle these errors in code and output a ``invalid file`` error message.

For example:
```
RUN: [Tue Jan 16 01:19:49 2018]
#!/usr/bin/bash
echo "{
"node": {
"bogusnode": {
"device_type": "server",
"obj_info": {
"groups": "test"
},
"obj_type": "node",
"role": "compute"
}
}
" > /tmp/xcat_inventory_import_option_f_invalid_file/invaild_json
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:

RUN:cat /tmp/xcat_inventory_import_option_f_invalid_file/invaild_json [Tue Jan 16 01:19:49 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
{
node: {
bogusnode: {
device_type: server,
obj_info: {
groups: test
},
obj_type: node,
role: compute
}
}


RUN:xcat-inventory import -f /tmp/xcat_inventory_import_option_f_invalid_file/invaild_json [Tue Jan 16 01:19:49 2018]
ElapsedTime:0 sec
RETURN rc = 1
OUTPUT:
Traceback (most recent call last):
  File "/opt/xcat/lib/python/xcclient/inventory/shell.py", line 51, in main
    InventoryShell('xcat-inventory').run(sys.argv[1:], '1.0', "xCAT inventory management tool")
  File "/opt/xcat/lib/python/xcclient/shell.py", line 184, in run
    return args.func(args)
  File "/opt/xcat/lib/python/xcclient/inventory/shell.py", line 33, in do_import
    mgr.import_all(args.path)
  File "/opt/xcat/lib/python/xcclient/inventory/manager.py", line 161, in import_all
    obj_attr_dict = yaml.load(contents)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 550, in parse_flow_mapping_key
    "expected ',' or '}', but got %r" % token.id, token.start_mark)
ParserError: while parsing a flow mapping
  in "<string>", line 1, column 1:
    {
    ^
expected ',' or '}', but got '<stream end>'
  in "<string>", line 13, column 1:

    ^

RUN: [Tue Jan 16 01:19:49 2018]
#!/usr/bin/bash
echo "node:
bogusnode:
device_type: server
obj_info:
groups: test
obj_type: node
role: compute
"  > /tmp/xcat_inventory_import_option_f_invalid_file/invaild_yaml
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:

RUN:cat /tmp/xcat_inventory_import_option_f_invalid_file/invaild_yaml [Tue Jan 16 01:19:49 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
node:
bogusnode:
device_type: server
obj_info:
groups: test
obj_type: node
role: compute


RUN:xcat-inventory import -f /tmp/xcat_inventory_import_option_f_invalid_file/invaild_yaml [Tue Jan 16 01:19:49 2018]
ElapsedTime:1 sec
RETURN rc = 1
OUTPUT:
Traceback (most recent call last):
  File "/opt/xcat/lib/python/xcclient/inventory/shell.py", line 51, in main
    InventoryShell('xcat-inventory').run(sys.argv[1:], '1.0', "xCAT inventory management tool")
  File "/opt/xcat/lib/python/xcclient/shell.py", line 184, in run
    return args.func(args)
  File "/opt/xcat/lib/python/xcclient/inventory/shell.py", line 33, in do_import
    mgr.import_all(args.path)
  File "/opt/xcat/lib/python/xcclient/inventory/manager.py", line 164, in import_all
    hdl.importObjs([], obj_attr_dict[objtype])
  File "/opt/xcat/lib/python/xcclient/inventory/manager.py", line 75, in importObjs
    for key, attrs in obj_attr_dict.items():
AttributeError: 'NoneType' object has no attribute 'items'

RUN:rm -rf /tmp/xcat_inventory_import_option_f_invalid_file [Tue Jan 16 01:19:50 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
```

**Comment by hu-weihua** [comment]
link to #4565
