### ISSUE TITLE
openbmc python agent exited unexpectedly

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#5257]
In a hierarchy environment, if define both MN and SN to  openbmc CN's attribute `servicenode`
It will show unexpected error when running remote control command, for example.
```
rpower butte[5-26] stat
butte7: on
butte8: on
Error: The xCAT Python agent does not exist. Check if xCAT-openbmc-py package is installed on management node and service nodes.
butte5: on
Error: Agent exited unexpectedly.  See /var/log/xcat/agent.log for details.
To revert to Perl framework: chdef -t site clustersite openbmcperl=ALL
```

And check the `/var/log/xcat/agent.log`, we can see the below error message:
```
xcat process exit unexpectedly.
Traceback (most recent call last):
  File "/opt/xcat/lib/python/agent/agent.py", line 58, in <module>
    AgentShell().main(sys.argv[1:])
  File "/opt/xcat/lib/python/agent/agent.py", line 47, in main
    s = server.Server(options.sock, options.standalone, options.lockfile)
  File "/opt/xcat/lib/python/agent/xcatagent/server.py", line 62, in __init__
    self.server = StreamServer(self._serve(), self._handle)
  File "/opt/xcat/lib/python/agent/xcatagent/server.py", line 66, in _serve
    listener.bind(self.address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use
```

**Comment by robin2008** [comment]
Although this is not a normal configuration to set `servicenode` to both MN and SN, but the error is caused by the concurrent supporting.

After investigation, it is a code error there. It try to use `$$` to define variable (socket file name) which could be changed in different process based on the PID. But it is in a perl module, we cannot get the expected value. As a consequence, two plugins in same time (with wrong configuration, it will hit such case) will try to use the same socket file and cause the 2nd one failed.
