### ISSUE TITLE
Failed to install CUDA from pkglist for diskfull osimage

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#6440]
we are trying to install CUDA with the rhel7.6 osimage.  it failed when install `CUDA` from pkglist, but works fine if install `CUDA` from otherpkglist.    the console showed: 
````
Creating prepboot on /dev/sda1
.
Running pre-installation scripts
.
Starting package installation process

An unknown error has occured, look at the /tmp/anaconda-tb* file(s) for more details

===============================================================================
An unknown error has occurred
===============================================================================
anaconda 21.48.22.134-1 exception report
Traceback (most recent call first):
  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 414, in next
    (self._argv, self._proc.returncode))
  File "/usr/lib64/python2.7/site-packages/pyanaconda/packaging/yumpayload.py", line 1563, in install
    for line in execReadlines("/usr/libexec/anaconda/anaconda-yum", args):
  File "/usr/lib64/python2.7/site-packages/pyanaconda/install.py", line 252, in doInstall
    payload.install()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/threads.py", line 227, in run
    threading.Thread.run(self, *args, **kwargs)
OSError: process '['/usr/libexec/anaconda/anaconda-yum', '--config', '/tmp/anaconda-yum.conf', '--tsfile', '/mnt/sysimage/anaconda-yum.yumtx', '--rpmlog', '/tmp/rpm-script.log', '--installroot', '/mnt/sysimage', '--release', '7.5', '--arch', 'ppc64le', '--macro', '__dbi_htconfig', 'hash nofsync %{__dbi_other} %{__dbi_perms}', '--macro', '__file_context_path', '/etc/selinux/targeted/contexts/files/file_contexts']' exited with status 1

What do you want to do now?
1) Report Bug
2) Debug
3) Quit
`````
these are the rpms in the pkglist:
````
%packages
wget
ntp
nfs-utils
net-snmp
rsync
yp-tools
openssh-server
util-linux
net-tools
kernel-devel
gcc
pciutils
dkms
vulkan-filesystem
cuda
%end
`````
the anaconda logs showed script error for the cuda-drivers:
````
19:14:52,448 INFO packaging:  check transaction set
19:14:52,526 INFO packaging:  order transaction set
19:14:52,543 INFO packaging:  running transaction
19:14:55,986 ERR packaging:  script error with package cuda-drivers
19:14:55,986 DEBUG packaging: Traceback (most recent call last):
19:14:55,986 DEBUG packaging: File "/usr/libexec/anaconda/anaconda-yum", line 213, in callback
19:14:55,986 DEBUG packaging: File "/usr/libexec/anaconda/anaconda-yum", line 400, in script_error
19:14:55,986 DEBUG packaging: Exception: script error
19:14:55,987 DEBUG packaging: FATAL ERROR: python callback <bound method RPMCallback.callback of <__main__.RPMCallback object at 0x7fffb8ae0710>> failed, aborting!
19:14:56,001 INFO packaging: ==== start rpm scriptlet logs ====
19:14:56,001 INFO packaging: warning: filesystem-3.2-25.el7.ppc64le: Header V3 RSA/SHA256 Signature, key ID fd431d51: NOKEY

19:14:56,001 INFO packaging: warning: cuda-drivers-418.87.00-1.ppc64le: Header V3 RSA/SHA512 Signature, key ID 7fa2af80: NOKEY

19:14:56,001 INFO packaging: error: %pretrans(cuda-drivers-418.87.00-1.ppc64le) scriptlet failed, exit status 127

19:14:56,001 INFO packaging: ==== end rpm scriptlet logs ====
````

**Comment by cxhong** [comment]
found root cause of this issue,  for cuda version `418.87.00-1`, the cuda-drivers has %pretrans scripts
```
# rpm -qp --scripts cuda-drivers-418.87.00-1.ppc64le.rpm
warning: cuda-drivers-418.87.00-1.ppc64le.rpm: Header V3 RSA/SHA512 Signature, key ID 7fa2af80: NOKEY
pretrans scriptlet (using /bin/sh):
if [[ ! $(which nvidia-uninstall 2&>/dev/null) ]]; then
    echo "Removing existing driver runfile install"
    nvidia-uninstall -s || :
fi
````
for older version of cuda-drivers, it doesn't contain any scriptlet.  
```
# rpm -qp --scripts cuda-drivers-418.67-1.ppc64le.rpm
warning: cuda-drivers-418.67-1.ppc64le.rpm: Header V3 RSA/SHA512 Signature, key ID 7fa2af80: NOKEY
````
i can provision this version of cuda on diskfull installation, had no problem.

**Comment by cxhong** [comment]
Mark Perez opened a Nividia bug for this issue , thanks.
https://partners.nvbugs.nvidia.com/BugReports/vwBugReport.aspx?bugID=2725715&sessargs=685f564eac024916b7cc1927d590f2c2

**Comment by cxhong** [comment]
replace dkms with nvidia-driver-latest-dkms and pkglist order matters too
```
$ cat common/pkglist/rhels76/cuda.df.pkglist
kernel-devel
gcc
pciutils
# Order matters below.
# provided by Server-optional
vulkan-filesystem
# from cuda repository
nvidia-driver-latest-dkms
cuda
```
